name: VoxelBorder
main: com.thevoxelbox.bukkit.border.VoxelBorder
version: MAVEN_VERSION
website: http://thevoxelbox.com
author: przerwap
description: >
             Limit your world by adding a border!
commands:
  voxelborder:
    description: Sets the border.
  vborder:
    description: Sets the border.
  btp:
    description: Needs a description.
    usage: |
           /<command>
           Example: /<command> - need to write the help.
