name: VoxelBorder
main: com.thevoxelbox.voxelborder.VoxelBorder
version: maven-version-number
website: http://thevoxelbox.com
authors: [TheCryoknight, przerwap]
description: >
             Limit your world by adding a border!
commands:
  voxelborder:
    aliases: vborder
    description: Sets the border.
  btp:
    description: Border Teleport.
    